
package com.knight.estoque.servicos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutoresServiceService", targetNamespace = "http://servicos.estoque.knight.com/", wsdlLocation = "https://localhost:8443/soa-cap06-estoque-0.0.1-SNAPSHOT/AutoresService?wsdl")
public class AutoresServiceService
    extends Service
{

    private final static URL AUTORESSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTORESSERVICESERVICE_EXCEPTION;
    private final static QName AUTORESSERVICESERVICE_QNAME = new QName("http://servicos.estoque.knight.com/", "AutoresServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://localhost:8443/soa-cap06-estoque-0.0.1-SNAPSHOT/AutoresService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTORESSERVICESERVICE_WSDL_LOCATION = url;
        AUTORESSERVICESERVICE_EXCEPTION = e;
    }

    public AutoresServiceService() {
        super(__getWsdlLocation(), AUTORESSERVICESERVICE_QNAME);
    }

    public AutoresServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTORESSERVICESERVICE_QNAME, features);
    }

    public AutoresServiceService(URL wsdlLocation) {
        super(wsdlLocation, AUTORESSERVICESERVICE_QNAME);
    }

    public AutoresServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTORESSERVICESERVICE_QNAME, features);
    }

    public AutoresServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutoresServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutoresService
     */
    @WebEndpoint(name = "AutoresServicePort")
    public AutoresService getAutoresServicePort() {
        return super.getPort(new QName("http://servicos.estoque.knight.com/", "AutoresServicePort"), AutoresService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutoresService
     */
    @WebEndpoint(name = "AutoresServicePort")
    public AutoresService getAutoresServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.estoque.knight.com/", "AutoresServicePort"), AutoresService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTORESSERVICESERVICE_EXCEPTION!= null) {
            throw AUTORESSERVICESERVICE_EXCEPTION;
        }
        return AUTORESSERVICESERVICE_WSDL_LOCATION;
    }

}
