
package com.knight.estoque.servicos;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutoresService", targetNamespace = "http://servicos.estoque.knight.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutoresService {


    /**
     * 
     * @return
     *     returns java.util.List<com.knight.estoque.servicos.Autor>
     */
    @WebMethod
    @WebResult(name = "autor", targetNamespace = "")
    @RequestWrapper(localName = "listarAutores", targetNamespace = "http://servicos.estoque.knight.com/", className = "com.knight.estoque.servicos.ListarAutores")
    @ResponseWrapper(localName = "listarAutoresResponse", targetNamespace = "http://servicos.estoque.knight.com/", className = "com.knight.estoque.servicos.ListarAutoresResponse")
    public List<Autor> listarAutores();

}
