//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.14 at 10:50:09 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://knight.com/estoque/domain/v1")
package com.knight.estoque.domain.v1;
