
package com.knight.estoque.services.autoresservice.v1;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutoresServiceCallback", targetNamespace = "http://knight.com/estoque/services/AutoresService/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.knight.estoque.domain.v1.ObjectFactory.class,
    com.knight.estoque.services.autoresservice.v1.ObjectFactory.class,
    com.knight.usuarios.domain.v1.ObjectFactory.class
})
public interface AutoresServiceCallback {


    /**
     * 
     * @param parameters
     */
    @WebMethod
    @Oneway
    public void solicitarRelacaoDeAutoresCallback(
        @WebParam(name = "solicitarRelacaoDeAutoresResponse", targetNamespace = "http://knight.com/estoque/services/AutoresService/v1", partName = "parameters")
        SolicitarRelacaoDeAutoresResponse parameters);

}
